require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Gemfile'
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'test/**/*'
