default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  database: houou_development

test:
  <<: *default
  database: houou_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
